### PR TITLE
Updates for data and tutorial from HNX

### PR DESCRIPTION
**Pull request by brendapraggastis**
merged the examples folder into tutorials, since Examples.ipynb really just illustrated to and from hif methods for hnx. Put all data used into tutorials/data folder.
Also, the json for diseasome and e-coli had errors (attr should have been attrs) so i fixed that.

### CODE REVIEW

**Comment by brendapraggastis** [comment]
@nwlandry and @colltoaction please have a look. I believe the formats are fine but notebooks won't run until I get approval to push HIF translators to HNX.

**Comment by colltoaction** [comment]
It looks good to me. Let me know when I can check the rest of the HNX code.

Thanks Brenda!

**Comment by nwlandry** [comment]
Looks great, @brendapraggastis! Thanks for all your work on this. Ready to merge!

**Comment by colltoaction** [comment]
@brendapraggastis just a friendly reminder that you need to update the pnnl repository

**Comment by brendapraggastis** [comment]
The pnnl hnx repository has a gatekeeper I must go through before pushing code. Will push as soon as it is cleared. Thanks.

__________________________________
Brenda Praggastis, PhD
Senior Data Scientist and Mathematician
Math, Stats & Data Science
AI & Data Analytics

Pacific Northwest National Laboratory
1100 Dexter Ave N, Suite 500
Seattle, WA 98109 USA
(206) 528-3409 (voice only)


From: Martin Coll ***@***.***>
Date: Wednesday, December 11, 2024 at 2:17 PM
To: pszufe/HIF-standard ***@***.***>
Cc: Praggastis, Brenda ***@***.***>, Mention ***@***.***>
Subject: Re: [pszufe/HIF-standard] Updates for data and tutorial from HNX (PR #23)
Check twice before you click! This email originated from outside PNNL.


@brendapraggastis<https://github.com/brendapraggastis> just a friendly reminder that you need to update the pnnl repository

**Pull request merged**
