### PR TITLE
Included additionalProperties for incidences, edges, nodes and updated tests

### PR DESCRIPTION
**Pull request by brendapraggastis**
Commits bfc6467 and 3a7f80e are consistent with the original intent, which was to allow the user to define properties on all elements of the node, edge, and incidence objects. For example, all edges could have a timestamp. Rather than adding it to attrs separately for each item we can define it directly as a common property. Either place would work but now both are allowed. This will make it easier to read in a hypergraph directly from a data table.

### CODE REVIEW

**Comment by brendapraggastis** [comment]
Updated examples to be consistent with standard and included tutorial on how these were created.

**Comment by colltoaction** [comment]
> Either place would work but now both are allowed

I see why one would want this but I think we shouldn't have both. From recent experience I would choose common properties over attrs.

**Comment by nwlandry** [comment]
> Commits [bfc6467](https://github.com/pszufe/HIF-standard/commit/bfc646729b15c61509df8b25eb76af8266a31c4f) and [3a7f80e](https://github.com/pszufe/HIF-standard/commit/3a7f80e4485a05d8c9b7f2855fdc1b84b105147b) are consistent with the original intent, which was to allow the user to define properties on all elements of the node, edge, and incidence objects. For example, all edges could have a timestamp. Rather than adding it to attrs separately for each item we can define it directly as a common property.

Based on the past group meetings, this schema is not what we decided upon. My impression from our discussions was to separate structural information (node, edge, weight, direction) from metadata (name, timestamp, etc.) by putting metadata in `attrs`. If I understand correctly, this change (from `attrs` to top-level properties) is to make it easy to read in a data table. Before committing to this change, I think we should all discuss at our meeting on Monday to see if this makes sense for the whole group.

> Either place would work but now both are allowed.

Unless I'm mistaken, on the main branch, both are not allowed, because `additionalProperties=false`.

**Comment by brendapraggastis** [comment]
@nwlandry The original schema allowed additionalProperties. I thought we agreed to remove that for the top level but keep for nodes, edges, and incidences. The reason to have both is some properties are common to all and some properties are instance specific. If I agreed to removing them everywhere then I hadn't thought it through.

Having additionalProperties is a convenience, and I'm not sure why we would place an arbitrary constraint on what data can be placed on these objects. For example, we already are getting requests to place edge specific orderings on incidences. It would be a convenience to have a property `index` on every incidence without having to place it in attrs. The attrs is there to allow some object to have properties not held by all other incidences.

In my mind it makes sense to limit the top level keywords and require identifiers on incidences, edges, and node. Beyond that, I feel we need to make the format as expressive as possible.

**Comment by brendapraggastis** [comment]
@nwlandry  I will close this and do a refactor. We can discuss the options more when we see the implications of implementing for only attrs.

**Pull request closed without merging**
