### PR TITLE
Update organization of the unit tests

### PR DESCRIPTION
**Pull request by nwlandry**
This PR does the following:

* Organizes the unit tests and files into two categories: HIF-compliant and HIF non-compliant. The unit tests are split into two files and the json files are put into two separate folders according to HIF compliance/non-compliance.
* Organizes `conftest.py` and the unit test files roughly in these categories: top-level attributes, metadata, nodes, edges, and incidences.
* Format the JSON files consistently (And the schema) with VSCode formatter (https://www.geeksforgeeks.org/how-to-format-json-in-vscode/)
* Adds several unit tests to the test suite
* Tweaks the README and License files.
* Tweaks the schema because it was not catching extraneous fields in the incidence records

### CODE REVIEW

**Comment by nwlandry** [comment]
Hi @colltoaction and @FraLotito --- would really appreciate your thoughts on these changes! I reorganized the unit tests to make them easier to contribute to.

**Comment by FraLotito** [comment]
Thanks @nwlandry! I'll check it out in the following days

**Review by colltoaction — APPROVED** [review]
I'm wondering if we can remove some duplication like `return json.load...` but I don't see any pytest feature to aid with this.

WRT formatting it would be good to understand what this formatter is doing but it's fine with me. An external formatter / linter could be ran in Actions for guardrailing.

Thank you!

**Review by FraLotito — APPROVED** [review]
Ok I agree with this structure, I think the changes improve the readability and organization of the tests. Thanks @nwlandry !

**Comment by nwlandry** [comment]
> I'm wondering if we can remove some duplication like `return json.load...` but I don't see any pytest feature to aid with this.
> 
> WRT formatting it would be good to understand what this formatter is doing but it's fine with me. An external formatter / linter could be ran in Actions for guardrailing.
> 
> Thank you!

Good point! I'll see what's out there.

**Comment by nwlandry** [comment]
@FraLotito and @colltoaction, thanks for reviewing!!

**Pull request merged**
